- adabot/circuitpython_libraries.py
I created a directories list.  Then just check for a examples folder.  Do you think we should check for one or more .py files in the examples folder as well?
> Added check for examples folder in library

- adabot/circuitpython_libraries.py
This means we'll validate forks that live under adafruit and can
also document third-party forks in the future.
> Include forks in validation.

- adabot/circuitpython_bundle.py
Also, tweak the release message and error handling.
> Handle moved and removed submodules more gracefully.

- adabot/circuitpython_libraries.py
- adabot/github_requests.py
* Remove old travis config error
* Move pypi to standard reporting
* Add pylint versioning checks
* Delete tokens that aren't added to Travis successfully
> Lotsa improvements

- adabot/circuitpython_libraries.py
Sample output here: https://gist.github.com/tannewt/2aff77377ab88df1e75d7610e0f06787
> Split some library stats and handle language

- adabot/circuitpython_library_download_stats.py
> Bundle & PyPi Download Stats

- adabot/circuitpython_libraries.py
Fixes #25.
@kattni decided to go ahead and move to a PR from issue discussion, since we're close if not done.
> Exclude New/Empty Repos From Most Checks

- adabot/arduino_libraries.py
Addresses "part 1" of #33.
Sample Output:
```
(.env) sommersoft@thespacebetween:~/Dev/adabot/adabot$ python3 -m adabot.arduino_libraries
Running Arduino Library Checks
3700 requests remaining this hour
3600 requests remaining this hour
3500 requests remaining this hour
Libraries Have Mismatched Release Tag and library.properties Version: (23)
Repo                                      Release Tag   library.properties Version   
----                                      -----------   --------------------------   
Adafruit_Pixie                            v1.1.0        1.1                          
TinyXML                                   v1.0.0        1.0.0                        
HT1632                                    v1.0.3        1.0.3                        
Adafruit_TiCoServo …
```
> Adabot Wants To Be Friends With Arduino!

- adabot/circuitpython_libraries.py
Fixes #41 
```
Core
* 11 pull requests merged
* 7 authors - dhalbert, ShawnHymel, tannewt, jimblom, TG-Techie, jerryneedell, hathach
* 2 reviewers - dhalbert, tannewt
* 7 open pull requests
* https://github.com/adafruit/circuitpython/pull/1404
* https://github.com/adafruit/circuitpython/pull/1370
* https://github.com/adafruit/circuitpython/pull/1365
* https://github.com/adafruit/circuitpython/pull/1363
* https://github.com/adafruit/circuitpython/pull/1274
* https://github.com/adafruit/circuitpython/pull/1144
* https://github.com/adafruit/circuitpython/pull/943
* 2 closed issues by 2 people, 7 opened by 5 people
* 158 open issues
* https://github.com/adafruit/circuitpython/issues
```
> Fix Issue Reporting For >100 Open Issues

- adabot/circuitpython_library_patches.py
Finally got around to doing this, when trying to see if patching the change to `travis-ci.com` in README would work.
This adds two command line arguments:
- `--dry-run`: Since `git apply --check` is already used, this simply force-skips the application of patches.
- `--local`: This adds the ability to run a patch that exists on the local machine, removing the requirement that the patch is approved/merged into the Adabot repo. It is only available for use with `--dry-run` and `--list`, so that you can't actually apply any patches that aren't approved.
Also, I made the error/failure reports a little prettier.
> Add Patch Testing Capability

- adabot/circuitpython_library_download_stats.py
This sorts the results by number of downloads (descending). Had to restructure some things, so that pypi stats that aren't retrieved didn't mess up the sorting (doesn't like text).
EDIT: forgot the beautiful sample...
```
Adafruit CircuitPython Library Download Stats
Report Date: 09 January 2019, 07:33PM
Adafruit_CircuitPython_Bundle downloads for the past week:
* adafruit-circuitpython-bundle-3.x-mpy: 296
* adafruit-circuitpython-bundle-4.x-mpy: 138
* adafruit-circuitpython-bundle-py: 64
* adafruit-circuitpython-bundle-examples: 60
* adafruit-circuitpython-bundle-2.x-mpy: 44
Adafruit CircuitPython Library PyPi downloads for the past week: 
* Adafruit_CircuitPython_CharLCD: 883
* Adafruit_CircuitPython_RFM69: 537
* Adafruit_CircuitPython_BusDevice: 412
* Adafruit_CircuitPython_seesaw: 290 …
```
> Sort Download Stats By Number Of Downloads

- adabot/circuitpython_library_download_stats.py
Addresses #52, with respect to PyPi total downloads stats.
Also tabulates the PyPi stats now that there are two values:
```
Adafruit CircuitPython Library PyPi downloads: 
Repo                                        Last Week   Total   
----                                        ---------   -----   
Adafruit_CircuitPython_CharLCD              870         5905    
Adafruit_CircuitPython_RFM69                551         4352    
Adafruit_CircuitPython_BusDevice            429         6961    
Adafruit_CircuitPython_seesaw               296         2050    
Adafruit_CircuitPython_TMP006               286         1672    
Adafruit_CircuitPython_TCS34725             282         2002    
Adafruit_CircuitPython_RFM9x                280         2011    
```
> Add Total PyPi Download Stats

- adabot/circuitpython_library_download_stats.py
Don't know how I missed that to begin with. Thanks for the eagle-eye @ladyada!
> Added Blinka To Download Stats

- adabot/circuitpython_libraries.py
- adabot/github_requests.py
- adabot/pypi_requests.py
- adabot/travis_requests.py
Fixes #59 
At least I hope it does, since I can't replicate Travis' failures.
> Mitigate Header Missing & Request Timeouts

- adabot/circuitpython_libraries.py
> Change 'drivers.rst' URL To the Bundle

- adabot/circuitpython_libraries.py
Fixes #54, and fixes the recent zeroes for all core insights (issues, PRs).
> Combine & Tabulate Board DL Stats; Fix Core Insights

- adabot/circuitpython_libraries.py
Fixes #68 
I wanted to use kwargs for this, but couldn't get the `validators` list to play nicely. So, it uses a top-level namespace variable. It works, and excludes in-work repos from each validator when running validators with the `-v` flag.
Also a minor tweak to ensure that `validate_contents` is run first if included with `-v` flag.
> Always Run `validate_contents` with `-v` Flag

- adabot/circuitpython_bundle.py
- adabot/circuitpython_libraries.py
- adabot/circuitpython_library_download_stats.py
- adabot/circuitpython_library_patches.py
- adabot/lib/circuitpython_library_validators.py
- adabot/lib/common_funcs.py
- tests/test_circuitpython_libraries.py
Refactor step 1, as outlined in #78.
I ran each main script except `patches`, and they behave as expected. Though that may change on Travis...
This will hopefully help with expansion (circuitpython.org) and maintainability going forward.
> Refactor CP Library Validators & Common Code

- adabot/lib/circuitpython_library_validators.py
Apparently, a subsequent commit I made locally during #89 to fix this, apparently didn't make it to GitHub. Now...it has.
> Fix SyntaxError

- adabot/update_cp_org_libraries.py
It must have been a late night..or something. 🤷‍♂
> Fix Mangling a Call To 'datetime'

- adabot/circuitpython_libraries.py
- adabot/lib/common_funcs.py
- adabot/update_cp_org_libraries.py
> Add List of New & Updated Libraries To Library Report

- adabot/circuitpython_bundle.py
> Updated Bundle Email Text with updated instructions

- adabot/github_requests.py
Ugly but it works. Tested by setting the timeout to 0.001
> Replace api key in error message

- adabot/lib/circuitpython_library_validators.py
- adabot/lib/common_funcs.py
> Expand Example File Checks To Include Subfolders

- .gitignore
- adabot/circuitpython_libraries.py
- adabot/lib/blinka_funcs.py
- adabot/lib/common_funcs.py
Fixes #119 & #121 
Example of new information:
```
Blinka
* 4 pull requests merged
* 2 authors - makermelissa, caternuson
* 3 reviewers - ladyada, makermelissa, tannewt
* 2 open pull requests
* https://github.com/adafruit/Adafruit_Blinka/pull/147 (Open 126 days)
* https://github.com/adafruit/Adafruit_Blinka/pull/201 (Open 2 days)
* 2 closed issues by 1 people, 3 opened by 3 people
* 25 open issues
* https://github.com/adafruit/Adafruit_Blinka/issues
* PyPI Downloads in the last week: 1775
Number of supported boards: 53
```
> Add Blinka To Daily Report

- adabot/lib/blinka_funcs.py
> Change Blinka Supported Board Count To Use circuitpython.org Information

- adabot/circuitpython_libraries.py
- adabot/lib/circuitpython_library_validators.py
- adabot/lib/common_funcs.py
Fixes #130.
Here is a full example:
[report.txt](https://github.com/adafruit/adabot/files/4142181/report.txt)
> Libraries: List Merged PRs

- adabot/circuitpython_libraries.py
Before:
```
State of CircuitPython + Libraries
Overall
* 51 pull requests merged
* 20 authors - kattni, theacodes, jimbobbennett, hierophect, makermelissa, tannewt, mfeif, FoamyGuy, jerryneedell, ladyada, Marius-450, fgallaire, brentru, sommersoft, dherrada, danlove99, iraytrace, jepler, arturo182, caternuson
* 12 reviewers - dhalbert, brentru, kattni, sommersoft, makermelissa, tannewt, FoamyGuy, jepler, jerryneedell, siddacious, ladyada, caternuson
* 13 closed issues by 8 people, 16 opened by 10 people
```
After:
```
State of CircuitPython + Libraries + Blinka
Overall
* 51 pull requests merged
* 20 authors - dherrada, jimbobbennett, tannewt, jepler, theacodes, fgallaire, iraytrace, sommersoft, ladyada, brentru, caternuson, kattni, mfeif, Marius-450, makermelissa, jerryneedell, …
```
> Add Blinka Stats To the 'Overall' Section

- adabot/lib/circuitpython_library_validators.py
Fixes #144 
I may have got a little too fancy, but I wanted to be able to handle cases of version pinning.
Example run:
```
(.env) ~/Dev/adabot/adabot:$> python3 -m adabot.circuitpython_libraries -v validate_contents -e 999
Running CircuitPython Library checks...                                                                             
Report Date: 11 March 2020, 09:33PM                                                                                 
- Depth for listing libraries with errors: 999                                                                     
- Prompts for the GitHub Token are disabled.
- These validators will run: validate_contents
Latest pylint is: 2.4.4
PyLint version not latest - 179
* https://github.com/adafruit/Adafruit_CircuitPython_DotStar
* …
```
> Re-establish Pylint Version Checks

- adabot/lib/circuitpython_library_validators.py
Fixes #155 
Instead of just flagging a repo for having missing labels, go ahead and add them.
Awesome `print` debug dry-run sample:
```
(.env) ~/Dev/adabot/adabot:$> python3 -m adabot.circuitpython_libraries -v "validate_labels"
Adafruit_CircuitPython_MLX90614: Adding "documentation" with color "d4c5f9"
Adafruit_CircuitPython_VL6180X: Adding "documentation" with color "d4c5f9"
Adafruit_CircuitPython_BluefruitSPI: Adding "documentation" with color "d4c5f9"
Adafruit_CircuitPython_MPL115A2: Adding "documentation" with color "d4c5f9"
Adafruit_CircuitPython_SharpMemoryDisplay: Adding "documentation" with color "d4c5f9"
Adafruit_CircuitPython_MCP9600: Adding "documentation" with color "d4c5f9"
Adafruit_CircuitPython_STMPE610: Adding "documentation" with color "d4c5f9" …
```
> Automatically Add Missing Standard Labels

- adabot/lib/circuitpython_library_validators.py
Fixes #161 
```
~/Dev/adabot/adabot:$> python3 -m adabot.circuitpython_libraries -v "validate_release_state"
Running CircuitPython Library checks...
Report Date: 07 April 2020, 01:53PM
- Depth for listing libraries with errors: 5
- These validators will run: validate_release_state
Adafruit_CircuitPython_CPython
updated files['README.rst']
non-CI/dot files: ['README.rst']
Adafruit_CircuitPython_Pypixelbuf
updated files['.github/workflows/build.yml', '.pylintrc', 'CODE_OF_CONDUCT.md', 'README.rst', 'adafruit_pypixelbuf.py', 'docs/conf.py', 'docs/examples.rst', 'examples/pypixelbuf_simpletest.py', 'setup.py']
non-CI/dot files: ['examples/pypixelbuf_simpletest.py', 'docs/examples.rst', 'adafruit_pypixelbuf.py', 'docs/conf.py', 'setup.py', 'README.rst']
------
Library has new commits since …
```
> Ignore Local/CI Changes When Flagging A Required Release

- adabot/circuitpython_libraries.py
- adabot/lib/circuitpython_library_validators.py
- adabot/lib/common_funcs.py
@ladyada Do you think you could run this to test? It should say that there are 4 good first issues, but I'm only getting one. I think that's due to the issues we're having with github since I'm not seeing those libraries when I have it print out all the libraries it found, but I just wanted to be sure.
> Now outputs the number of good first issues

- adabot/circuitpython_libraries.py
- adabot/update_cp_org_libraries.py
> Add cookiecutter to Adabot

- adabot/lib/circuitpython_library_validators.py
- adabot/update_cp_org_libraries.py
Fix a bug where an error was a string instead of a list.
>  Fix a bug where an error was a string instead of a list.

- patches/0001-Removed-pylint-process-from-github-workflow-patch-2.patch
The previous one didn't work on all but ~10 libraries since I forgot to do -U0 when making the patch.
> Pylint patch 2

- patches/0001-Re-added-pylint-install-to-build.yml.patch
Tested:
failing: https://github.com/adafruit/Adafruit_CircuitPython_DS3502/runs/2017252347?check_suite_focus=true
passing: https://github.com/adafruit/Adafruit_CircuitPython_DS3502/runs/2017288885?check_suite_focus=true
> Added re-adding pylint install patch

- adabot/lib/circuitpython_library_validators.py
This should ignore all ci-related changes
> Added more files to be ignored by release check

- patches/0001-Added-help-text-and-problem-matcher.patch
- patches/0001-Added-pull-request-template.patch
Changes tested here: https://github.com/adafruit/Adafruit_CircuitPython_BNO055/pull/83
> Added help text and pr template patches

- adabot/circuitpython_libraries.py
- adabot/circuitpython_library_download_stats.py
Saw this mentioned here: https://github.com/piwheels/piwheels/issues/82 so thought I'd throw something together.
API reference: https://www.piwheels.org/json.html
It's half tested, half baked and not nicely formatted but hope it helps
> Add piwheels stats

- requirements.txt
> Remove Frozen Library Dependencies

- adabot/update_cp_org_libraries.py
- tests/integration/test_arduino_libraries.py
- tests/integration/test_circuitpython_libraries.py
- tests/integration/test_update_cp_org_libraries.py
- tests/unit/test_common_funcs.py
Adds more tests for the following:
- Integration:
- adabot/update_cp_org_libraries.py
- Unit:
- adabot/lib/common_funcs.py::sanitize_url()
- adabot/lib/common_funcs.py::get_docs_link()
- adabot/lib/common_funcs.py::is_new_or_updated()
> Add More Tests

- patches/0001-Added-pylint-disable-for-f-strings-in-tests-director.patch
Test PR: https://github.com/adafruit/Adafruit_CircuitPython_Debouncer/pull/30
> Added patch for f string check in tests dir

- patches/0001-First-part-of-patch.patch
This is the only one that can be done automatically-ish
> Added patch file

- requirements.txt
> Revert "Pin the pylint version to what the libraries are using"

- .gitignore
- adabot/lib/circuitpython_library_validators.py
This fixes the recent CI errors that have been happening, due to deleted GitHub user accounts.  I also added `.venv` to the .gitignore to patch the libraries' eventual change.
> Fix daily report

- .github/workflows/reports_cron.yml
Should have been done as part of #304
> Add new secrets to cron as environment variables

- adabot/circuitpython_libraries.py
Previous PR mishandled how iteration needs to happen over the query results
> Fix iteration over results

- adabot/lib/circuitpython_library_validators.py
The check now compares the files from cookecutter with the file in each repo
> Re-did pre-commit-config check

- adabot/lib/circuitpython_library_validators.py
Required after https://github.com/adafruit/Adafruit_CircuitPython_Bundle/pull/413
> Update RTD link check

- patches/01SEP2022_venv_gitignore.patch
Patch for adding `.venv` to all of the libraries' `.gitignore`
```shell
.... Working directory: /home/tekktrik/Documents/Repositories/adabot
.... Library directory: /home/tekktrik/Documents/Repositories/adabot/.libraries/
.... Patches directory: /home/tekktrik/Documents/Repositories/adabot/patches/
.... Deleting any previously cloned libraries
.... Running Patch Checks On 318 Repos ....
. Skipping Adafruit_CircuitPython_JTAG: patch does not apply
. Skipping Adafruit_CircuitPython_MachXO: patch does not apply
. Skipping Adafruit_CircuitPython_PCF8574: patch does not apply
. Skipping Adafruit_CircuitPython_ProgressBar: patch does not apply
. Skipping Adafruit_CircuitPython_Bundle: patch does not apply
.... Patch Updates Completed ....
.... Patches Applied: …
```
> Add patch for adding .venv to library .gitignore

- adabot/circuitpython_libraries.py
Fixes a parsing error caused by the failure to account for the Blinka stats now being in a table
> Fix parsing error

- adabot/circuitpython_libraries.py
> Fix truncation bug for library PyPI downloads

- adabot/lib/circuitpython_library_validators.py
Oops, here's the fix!  Tested.
> Fix adabout error with labelling draft PRs

- patches/01192023_release_patch.patch
Patch needed to make the libraries work with the new release action.
> Add release asset uploader patch

- adabot/circuitpython_libraries.py
Makes the weekly report more readable
> Combine Adafruit and Community Bundle updates

- patches/09MAY2023_precommit_update.patch
Updates `pylint` and other `pre-commit` hooks
> Add pre-commit patch

- adabot/circuitpython_bundle.py
Fixes the image links in the markdown files
> Fix image links

- adabot/circuitpython_libraries.py
@ladyada 
Show a summed total of libraries in the reports used during public meetings, as mentioned by @TheKitty.
> show total libraries too
