adafruit/adabot

- adabot/circuitpython_libraries.py
- adabot/github_requests.py
- adabot/travis_requests.py
- tests/test_circuitpython_libraries.py
Update to the circuitpython_libraries script to validate CircuitPython module repositories are included in the bundle.  This adds a new error string to the output and prints all the associated missing libraries, for example here's part of the new output:
```
Not in bundle. - 12
https://github.com/adafruit/Adafruit_CircuitPython_EPD
https://github.com/adafruit/Adafruit_CircuitPython_SGP30
https://github.com/adafruit/Adafruit_CircuitPython_VS1053
https://github.com/adafruit/Adafruit_CircuitPython_DS18X20
https://github.com/adafruit/Adafruit_CircuitPython_OneWire
https://github.com/adafruit/Adafruit_CircuitPython_AMG88xx
https://github.com/adafruit/Adafruit_CircuitPython_seesaw
https://github.com/adafruit/Adafruit_CircuitPython_Thermal_Printer …
```
> Add validation that modules are included in bundle to circuitpython_libraries script, and other small refactors.

- .gitignore
- README.rst
- adabot/circuitpython_library_patches.py
- patches/0001-updated-CoC.patch
This will apply any patch that exists in the `patches` directory to all CircuitPython Libraries (Adafruit Bundle only; could probably extend to the Community Bundle would just need to tweak the search for library repos).
Patch files are created using `git format-patch`, and applied with `git am`. See updated README.rst.
This initial PR keeps my testing setup, uses my GitHub forks of the libraries, and pushes to branches. Final settings/values are commented out, and any extra bits for the test setup are contained in comment blocks.
Here are sample outputs. I thought about dropping log files vs printing to screen; would be an easy addition.
Good Run:
```
(.env) vagrant@ubuntu-xenial:~/source/adabot$ python3 -m adabot.circuitpython_library_patches
.... …
```
> Add CircuitPython Library Patching Utility

- adabot/circuitpython_library_patches.py
- patches/0001-force-Travis-to-use-pylint-version-1.9.2-to-avoid-ne.patch
- Patch Script Fix: added exception handling for `__main__` in case the `.libraries` folder doesn't exist yet.
- New Patch: updates `.travis.yml` to force use of pylint v1.9.2; avoids applying new rules in pylint v2.0.
> Patch Script Fix & New Patch For pylint

- adabot/circuitpython_bundle.py
Added functions to sync `circuitpython_lib_list.md` when new libraries are added to the bundle. The list was a request from PT to ease blog posts for the available libraries (at minimum; could be used elsewhere).
I tested this up to commit; did not test pushing and releasing. Push seems straightforward enough, and the way I understand the release code, updates to the list won't make it into the release notes.
Diff before commit:
Commit log:
> Sync 'circuitpython_library_list.md'

- adabot/circuitpython_libraries.py
- requirements.txt
- Fixes #18.
- Also updates `requests` module to v2.20.0, as installed by requirements.txt. This is due to a vulnerability fix ([CVE-2018-18074](http://docs.python-requests.org/en/latest/community/updates/#id1)).
While testing this upgrade on my computer, I experienced endless hangs. After an arduous search, I came across this note on [timeouts](http://docs.python-requests.org/en/master/user/quickstart/#timeouts), which at least allowed requests to progress. I set `timeouts = 5`; anything below that usually resulted in timeout errors.
> Validate Release State and Upgrade 'requests' Module

- adabot/circuitpython_libraries.py
- adabot/circuitpython_library_download_stats.py
When I updated `list_repos()` a while back to only return Adafruit owned `Adafruit_CircuitPython` repos, it seemed to drop `circuitpython` core repo which was causing this:
```
State of CircuitPython + Libraries
Overall
* 23 pull requests merged
* 7 authors - dhalbert, kattni, tannewt, caternuson, process1183, ladyada, brennen
* 5 reviewers - dhalbert, tannewt, kattni, caternuson, brennen
* 10 closed issues by 4 people, 5 opened by 4 people
Core
* 0 pull requests merged
* 0 authors -
* 0 reviewers -
* 0 open pull requests
* 0 closed issues by 0 people, 0 opened by 0 people
* 58 open issues
* https://github.com/adafruit/circuitpython/issues
```
This PR fixes that...
> Fix 'list_repos()'

- adabot/circuitpython_libraries.py
- adabot/circuitpython_library_download_stats.py
- adabot/github_requests.py
- adabot/pypi_requests.py
- adabot/travis_requests.py
This moves `timeout=n` for `requests.get()` to the appropriate "getters": `github_requests.py`, `pypi_requests.py`, and `travis_requests.py`. For any calls in other scripts that directly call `requests.get()`, the timeout is set inline.
Also updated all timeouts to 30 seconds. This would be "serious internet trouble" levels.
> More Appropriate requests Timeouts

- .travis.yml
Fixes #16.
**This _will_ require some external setup.**
- Set the following environment variables:
- ADABOT_GITHUB_ACCESS_TOKEN
- ADABOT_TRAVIS_ACCESS_TOKEN
- ARTIFACTS_KEY=(AWS access key id)
- ARTIFACTS_SECRET=(AWS secret access key)
- ARTIFACTS_BUCKET=(S3 bucket name)
- ARTIFACTS_REGION (if it isn't the default "us-east-1")
- Turn off:
- Build pushed branches
- Build pushed pull requests
- Add a cron job to run `daily`
I've never worked with any AWS buckets, so these are guesses:
- Create `/adabot` directory, if needed. Travis will push the artifacts there (currently)
- Allow Adabot's Travis write access
@tannewt please give this a good look. I've used both the bundle's and core's `.travis.yml`s to work through this. However, it was also done with a lot of documentation reading.
I ran …
> Run Adabot On Travis

- adabot/circuitpython_libraries.py
Fixes #24 
The core insights still run every time; I can remove that if desired.
Example:
```
(.env) sommersoft@thespacebetween:~/Dev/adabot/adabot$ python3 -m adabot.circuitpython_libraries -v "validate_release_state"
Latest pylint is: 2.2.0
Found 120 repos to check.
Found 114 submodules in the bundle.
Running GitHub checks as sommersoft
Running Travis checks as sommersoft
4300 requests remaining this hour
4200 requests remaining this hour
4100 requests remaining this hour
4000 requests remaining this hour
3900 requests remaining this hour
3800 requests remaining this hour
State of CircuitPython + Libraries
Overall
* 13 pull requests merged
* 9 authors - C47D, tannewt, jerryneedell, dhalbert, pdp7, sommersoft, kattni, caternuson, adammhaile
* 5 reviewers - ladyada, brennen, dhalbert, …
```
> Validators - A La Carte

- adabot/circuitpython_libraries.py
There are a few repos that had `.readthedocs.yml` committed separate from the cookiecutter, and as such have a different SHA assigned to the file. Adding the SHA to adabot seems easier than git-fuing the files to match the other SHA.
> Add An SHA To "Mismatched .readthedocs.yml"

- .travis.yml
- adabot/circuitpython_libraries.py
Fixes the syntax error I introduced with #38. Boneheaded me didn't enclose the conditional with parens. I ran it locally after this fix; runs fine.
Also removed `sudo: false` from .travis.yml, since Travis is now ignoring it and having everything run in a VM.
> Fix Syntax Error And Remove Travis Container (sudo: false)

- .travis.yml
- adabot/arduino_libraries.py
Fixes step 2 in #33, by checking if/how many commits have been made to an Arduino library since its last release.
Also adds the Arduino library script to run on Travis and deploy to the AWS bucket.
Release "status" is output like so:
```
Libraries have commits since last release: (83)
Repo                                     Latest Release   Commits Behind   
----                                     --------------   --------------   
HL1606-LED-Strip-PWM                     1.0.0            2                
Adafruit-HX8340B                         1.0.0            2                
Adafruit-Flora-Pixel-Library             1.0.0            2                
Adafruit_TLC5947                         1.0.2            2                
Adafruit_SoftServo                       1.0.0 …
```
> Add Arduino Release "Status" & Add Arduino Checks To Travis

- adabot/circuitpython_libraries.py
The download stats function in `circuitpython_libraries.py` was assigning the published date for releases to a variable. A few days ago, the Travis cron job started failing on the assignment, because the pub date was returning `None`.
I tried to verify this by running the API call for releases in a web browser, which didn't provide any insight.
I then inserted some debug prints in the script, and realized that the API response was including the draft release for `4.0.0-alpha.4`. The draft release wasn't returned in the web browser; weird.
At any rate, the variable with the published date isn't used anywhere, so the simplest fix: don't assign it. 😄
> Fix Unecessary Failure

- adabot/circuitpython_libraries.py
- adabot/travis_requests.py
- template-env.sh
This updates Travis requests to use `.com` vs `.org`.
**This requires token updates!**
`.com` and `.org` tokens are **not** interchangeable. `ADABOT_TRAVIS_ACCESS_TOKEN` will need to be updated in your personal usage (env.sh), as well as the Adabot-on-Travis environment variable.
I added a non-interchangeable token note to `template_env.sh`.
> Travis Migration Update

- adabot/circuitpython_libraries.py
Fixes #49.
Categorizes the `validate_release_state()` results into time deltas: new commits over a month old, within the last month, and within the last week. Also appends the number of days since the oldest commit to the repo link.
```
(.env) sommersoft@thespacebetween:~/Dev/adabot/adabot$ python3 -m adabot.circuitpython_libraries -v "validate_release_state" -e 200
blah
blah
blah
Library has new commits since last release within the last month. - 101
* https://github.com/adafruit/Adafruit_CircuitPython_BoardTest (26 days)
* https://github.com/adafruit/Adafruit_CircuitPython_PCA9685 (19 days)
* https://github.com/adafruit/Adafruit_CircuitPython_DS2413 (19 days)
* https://github.com/adafruit/Adafruit_CircuitPython_FocalTouch (19 days)
* …
```
> Improve Visibility of Repos Needing Release

- adabot/circuitpython_library_download_stats.py
Couple tweaks to the PyPi stats:
- Renamed the `Repo` header to `Library`. Since this list is now used in the newsletter, seems a better description.
- Forced `align: left` in the Markdown table for the (now) `Library` column. When rendered in the newsletter, I think the `<center>` tag that wraps all of the content was forcing it to align center, which makes it a little difficult to read.
> Small Updates To DL Stats

- .travis.yml
- adabot/circuitpython_libraries.py
I did two things with this, which are primarily just to get some more debugging info on #59.
- Switched the Travis OS from Trusty to Xenial
- Added some startup messaging to help see where the jobs are actually failing. I _think_ its the API call to PyPI to get the latest version of pylint. This should help narrow that down.
> Further Debugging Travis Failures

- adabot/circuitpython_libraries.py
Fixes #63.
I was tempted to remove `ERROR_RTD_MISSING_LATEST_RELEASE` (the "Ignore me!" one), but decided not to. Also, couldn't find any way to make it be reliable info.
> Fix 'ERROR_RTD_VALID_VERSIONS_FAILED'

- .travis.yml
During some testing on the idle timeouts with the Travis cron jobs, I finally narrowed down that the stdout was being buffered. So, just needed to add the `-u` to the script calls to have the stdout go straight to the console unbuffered. Hopefully this will let us close #59 within the next week.
I also switched the .yaml to separate the bundle update and running reports into different matrices.
I dropped `cache: pip` early on in this round of debugging. Forgot to add it back in, but the pip install times are insignificant so..meh. I may add it in later if this build stays stable.
> Reduce Travis Log Ouput Idle Time

- adabot/circuitpython_libraries.py
Fixes #67.
This adds checks for `ure vs re`, `ujson vs json`, and `uerrno vs errno`. Combined them with the previous validator for `ustruct`.
> Add Additional CPython Strict Module Name checks.

- adabot/circuitpython_libraries.py
This started out as a debugging operation to address the library insights always returning zeroes. 
After a couple days of trying to debug that, I finally realized that `list_repos()` was only returning 120-125 repos. The repos that weren't showing up, were coincidently the ones that were updated recently.
So, I dropped the `in:name` and `fork:true` from the search string, and added `user:adafruit`. This resulted in 149 repos being returned, which seems **much** closer to the actual number of library repos.
And, it caused this:
```
Libraries
* 15 pull requests merged
* 8 authors - makermelissa, brentru, martymcguire, kattni, demophoon, jerryneedell, willingc, ladyada
* 5 reviewers - makermelissa, kattni, brentru, siddacious, ladyada
```
I also changed the `since` date formatting for the …
> Fix Dropped Repos

- adabot/circuitpython_libraries.py
Fixes #73 
Was a simple fix, using the milestones API.
```
Core
* 10 pull requests merged
* 5 authors - deshipu, penguindustin, dhalbert, sommersoft, siddacious
* 2 reviewers - dhalbert, tannewt
* 8 open pull requests
* https://github.com/adafruit/circuitpython/pull/1610
* https://github.com/adafruit/circuitpython/pull/1600
* https://github.com/adafruit/circuitpython/pull/1534
* https://github.com/adafruit/circuitpython/pull/1423
* https://github.com/adafruit/circuitpython/pull/1415
* https://github.com/adafruit/circuitpython/pull/1365
* https://github.com/adafruit/circuitpython/pull/1363
* https://github.com/adafruit/circuitpython/pull/1274
* 6 closed issues by 2 people, 6 opened by 5 people
* 151 open issues
* https://github.com/adafruit/circuitpython/issues
* 5 active milestones
* 3.x: …
```
> Add Core Milestone Insights

- adabot/circuitpython_bundle.py
Makes [Bundle PR #159](https://github.com/adafruit/Adafruit_CircuitPython_Bundle/pull/159) permanent. Thanks to @george-hawkins for the initial fix; sorry adabot reverted it on you.
> Update Bundle Blinka Image Location

- .gitignore
- adabot/github_requests.py
- adabot/lib/circuitpython_library_validators.py
- adabot/update_cp_org_libraries.py
- requirements.txt
Fixes #77.
With the move to updating CP.org, see discussion in that repo. [Issue #119](https://github.com/adafruit/circuitpython-org/issues/119) [PR #156](https://github.com/adafruit/circuitpython-org/pull/156)
I blocked the repo updating to only occur when run in Travis. To use manually, include the flag `-o <filename>`, and the JSON file will be saved. Or, just let it print out to the terminal...which always happens.
After this is merged, we can then submodule it into the CP.org repo, and have Travis run it.
This also updates the version of `urllib3`, which was identified as having a vulnerability.
> Add CP.org Libraries Update Script

- adabot/circuitpython_libraries.py
- requirements.txt
All of the Library open issues and infrastructure errors are now on circuitpython.org. So, the `circuitpython_libraries.py` report now only points to that location. Example of new runs: https://gist.github.com/sommersoft/8d41ff618d52d42a1993a7133e651c81
- Open PRs, and contributor/reviewer information is still gathered and listed.
- Infrastructure validators can still be run using the `-v` command line arg. Added the ability to use `-v all` to run all validators, and retained `-v "validator_1, validator_2, ..."`.
- Did a smidge of PEP8 cleanup. Which makes the diff really hard to read...sorry.
- Removed some old debug `print`s, and also fixed an exception handler that I had commented out previously.
> Prune Issue Info From Report

- adabot/lib/circuitpython_library_validators.py
Before this commit the `LIBRARY_DOESNT_NEED_BLINKA` string was being
treated as a list so non of the repos were matching the libraries which
didn't require blinka.
This commit replaces that variable with a list and adds in the
additional libraries which do not require blinka.
Fixes #70
> Fix 'Blinka library required' false-positives

- adabot/circuitpython_libraries.py
- adabot/lib/circuitpython_library_validators.py
During `validate_contents`, the check to make sure each example is prefixed with the library name, the repo's name was used. The `rfind()` was set to look for the first `_`, which resulted in errors when the repo had an extra underscore beyond `CircuitPython`. Example: `Adafruit_CircuitPython_Thermal_Printer` gave a lookup string of `printer`.
This changes the the `rfind()` to look for `CircuitPython_` instead, ensuring that the whole library name is captured.
Also fixed a couple latent bugs from the refactor, wrt to the `-v` command line flag.
> Fix Example Checks

- adabot/update_cp_org_libraries.py
- requirements.txt
- Updates `urllib3` to v1.24.3, which fixes the CVE-2019-9740 vulnerability.
- Fix Travis should run date handling:
- Switch to using ISO weekday; 1-7 vice 0-6. `.strftime("%A")` apparently uses ISO, even though the docs don't mention it.
- Fix the calculation of the should run date, compared to the current date.
> Update urrlib3; Fix cp.org/libraries Travis "Should Run"

- adabot/lib/circuitpython_library_validators.py
Fixes #87. (Fix is in lines 528-530)
There are a few that remain:
- https://github.com/adafruit/Adafruit_CircuitPython_GFX
- We could maybe add this one to the ignore list. Its not in the bundle...
- https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO
- Repo name is `AdafruitIO`, but the package/example files use an underscore: `adafruit_io`.
- https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display
- examples are named `rgbdisplay_`. Another re-name would fix this one.
- Multi Variant Libraries:
- https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15
- https://github.com/adafruit/Adafruit_CircuitPython_MCP3xxx
- https://github.com/adafruit/Adafruit_CircuitPython_AMG88xx
- These contain examples/simpletests for some of their variants. I think having them as they are …
> Don't Check non-.py Example Filenames For the Library Name

- adabot/update_cp_org_libraries.py
`TRAIVS != TRAVIS`
Also PEP8'd some more stuff, as I'm trying to get adabot to adhere a little more.
> Fix Typo For CP.org Script

- adabot/circuitpython_libraries.py
Just needed to tweak it a little, since now both the stable and pre-releases will have multiple languages.
```
Download stats by language:
| Board            | 4.0.1  | 4.0.0-rc.3  |
| -----------------|--------|-------------|
| ID               |   7    |      0      |
| de_DE            |   28   |      4      |
| en_US            |  1914  |     533     |
| en_x_pirate      |   31   |      6      |
| es               |   47   |      5      |
| fil              |   2    |      0      |
| fr               |   55   |     10      |
| it_IT            |   7    |      2      |
| pl               |   8    |      1      |
| pt_BR            |   10   |      5      |
| zh_Latn_pinyin   |   5    |      1      |
| -----------------|--------|-------------|
|            Total |  2114  |     567     | …
```
> Fix Download Stats By Language

- adabot/circuitpython_bundle.py
Fixes #98.
Thanks to @sommersoft for working on this with me. It took a lot of trial and error to figure out the right `git rev-list` arguments.
> Exclude releases that are not x.x.x

- adabot/update_cp_org_libraries.py
Submit PR for updates to `circuitpython-org/_data/libraries.json`, instead of directly pushing commits.
Fixes Travis cron failures like this: https://travis-ci.com/adafruit/circuitpython-org/builds/119066499
> Submit PRs To circuitpython-org Repo

- adabot/arduino_libraries.py
- adabot/github_requests.py
added:
* missing travis validator (checks if repo has .travis.yml)
* has *.ino validator (checks if repo has any ino files)
* has *.library.properties (checks if repo has library.properties) file
also as limits for github API `search` was lower found that the code runs too early when rate limit is reached and fixed the calculations problem (there was one sec difference that trigger while loop infinitely).
there is also some todos:
- make possible to run every check separately from cli
- displaying / logging limits is now a little bit messy, should be fixed
> missing travis + has ino + has library.properties + github delay hotfix

- adabot/lib/circuitpython_library_validators.py
Also, escapes repo contents check correctly when the repo is empty.
> Fix driver doc check to find url with - instead of _

- adabot/circuitpython_libraries.py
- adabot/lib/circuitpython_library_validators.py
- adabot/lib/common_funcs.py
- adabot/update_cp_org_libraries.py
This PR got a little out of hand, as multiple things got rolled into it.
Add "Days Open" Metrics
------------------------------
- Calculates the number of days that an issue or PR has been open.
- Applies to `circuitpython_libraries` and `update_cp_org_libraries`.
- Appends the number of days open to the issue/PR on reports
Validate Issue Lables
------------------------
- Adds a new validator to check the available issue labels on each library.
- Standard labels are: `bug, documentation, enhancement, good first issue`
circuitpython.org/libraries Transition to AWS
--------------------------------------------------
- Removes the check that ensured `update_cp_org_libraries` was only run once a week, on a certain day. New system will run daily.
- Removes the function & call that created a PR …
> Add "Days Open" Metrics; Validate Issue Labels; CirPy.org AWS Transition; Misc Maintenance

- adabot/lib/assign_hacktober_label.py
Here is the standalone script to automate assignment of the `Hacktoberfest` label to issues that have the `good first issue` label assigned.
To run: `python3 -m adabot.lib.assign_hacktober_label`
As far as getting this to run on a regular basis, here are my thoughts:
- Call from either `circuitpython_libraries.py` or `update_cp_org_libraries.py`, as they both run daily. `circuitpython_libraries` is my preference since it isn't tied to circuitpython.org, already includes the core repo, and has plenty of room left on API ratelimit (this currently uses around 300 requests).
- Use a date range to both add and remove the label.
- 30 September thru 31 October: check daily for missing label to catch new issues, and add the Hacktoberfest label as necessary.
- 1 November thru 29 September: check …
> Automate Hacktoberfest Label

- adabot/circuitpython_libraries.py
- adabot/lib/assign_hacktober_label.py
- adabot/lib/circuitpython_library_validators.py
This adds Hacktoberfest labeling to `circuitpython_libraries` so it is run daily:
- 29 September thru 30 October: Hacktoberfest label is added to any open issue with `good first issue` label.
- 1 November thru 10 November: Hacktoberfest label is removed from any open issue that has it.
- The rest of the year: isn't run or reported...
> Schedule Hacktoberfest Labeling

- adabot/update_cp_org_libraries.py
As requested in [cirpy.org 306](https://github.com/adafruit/circuitpython-org/issues/306), this adds any assigned labels to the issues list in `libraries.json`.
Also cleaned up some code from when updates were being pushed to GitHub (Pre-AWS).
> Cirpy.org: Add Label Data to Issues

- adabot/lib/circuitpython_library_validators.py
This changes the `validate_contents` step that checked for the existence of `.travis.yml`, and uses that to determine if a repo still needs to be migrated to GitHub Actions.
I also disabled/no-op'd all other TravisCI checks for now. I will do a full cleanup when adabot herself is migrated to GitHub Actions.
Verification run:
[adabot_migrate_actions.txt](https://github.com/adafruit/adabot/files/3795955/adabot_migrate_actions.txt)
> Change Travis Checks to Keep Track of Actions Migration

- adabot/lib/assign_hacktober_label.py
`lable` is not a word, and also not an available variable.
> Fix Typo In Hacktoberfest Label Handler

- .github/workflows/bundle_cron.yml
- adabot/circuitpython_bundle.py
This fixes the Redis connection error, by passing the correct (forwarded) port from the Docker redis image.
Successful test can be seen [here](https://github.com/sommersoft/adabot/runs/348142271).
> Fix Redis Connection Error For Bundle Cron

- .github/workflows/bundle_cron.yml
This fixes, again, the Redis instance in `bundle_cron.yml`. Failed transcription on previous PR...
> Another Fix for bundle_cron.yml

- adabot/circuitpython_libraries.py
This is to better handle the failure we're currently having with the API request to get download statistics for the CircuitPython core. I ran a local test, and it gets past the error just fine.
An example of the current failure can be seen at this link: https://api.github.com/repos/adafruit/circuitpython/releases
```
{
"message": "Server Error"
}
```
And the header info:
```
Request URL: https://api.github.com/repos/adafruit/circuitpython/releases
Request Method: GET
Status Code: 502 Bad Gateway
Remote Address: 192.30.255.117:443
Referrer Policy: no-referrer-when-downgrade
```
I don't have a good handle on why the API request is failing, as it passes on a lot of the other repos I've tried by hand. To include my own fork of the core repo. 🤷‍♂
> Daily Report: Handle Core Download Stats Request Failure

- README.rst
- adabot/github_requests.py
- template-env.sh
The use of `access_token` query parameters with the GitHub API [has been deprecated](https://developer.github.com/changes/#authenticating-using-query-parameters).
This change conforms to the use of the new scheme using HTTP Basic authentication.
I ran both `circuitpython_libraries.py` and `update_cp_org_libraries.py`, and both function as expected.
**Required updates:**
- `ADABOT_GITHUB_USER=<username>` which is attached to the access token must be available in the environment variables. Affects this repository and circuitpython-org.
- If you want to run it locally, you'll also need to add that envvar to your env (`env.sh`)
@tannewt, I left the exception handling that kept tokens from leaking to stdout. I'm _fairly_ certain they won't be needed now, since the token won't make it to the …
> Switch To New GitHub API Authentication Scheme

- .github/workflows/bundle_cron.yml
- .github/workflows/reports_cron.yml
As mentioned in https://github.com/adafruit/adabot/pull/138#issuecomment-582993992, this updates the GitHub Actions workflows to make the `ADABOT_GITHUB_USER` environment variable available.
I used an assumptive `secrets.ADABOT_GITHUB_USER` source; let me know if it needs to be changed.
> Update Actions To Use New Environment Variable

- adabot/circuitpython_libraries.py
- adabot/lib/circuitpython_library_validators.py
- adabot/update_cp_org_libraries.py
Fixes #134. 
- Adds Community Bundle issue and pull request stats to the daily report and the circuitpython.org/contributing scripts.
- For the circuitpython.org addition, the Community Bundle is not subjected to the infrastructure validators.
- Mitigated some `KeyError` exceptions I was getting in `validate_repo_state()`. The GitHub API results were missing the `license` and `permissions` keys. I couldn't find anything regarding changes to the API, and the circuitpython.org Actions job doesn't seem affected. Were there some access restrictions made?
> Add Community Bundle

- adabot/circuitpython_libraries.py
Fixes #136
- Temporarily disable `print_circuitpython_download_stats()`
- Print link to https://circuitpython.org/stats
- Add todo notes about getting stats from AWS CloudFront/CloudWatch via `boto3`
> Disable Core Download Stats

- adabot/lib/common_funcs.py
- patches/0001-update-code-of-conduct-discord-moderation-contact-sec.patch
- `common_funcs.py::list_repos()`: I had removed the `forks:true` from the search query quite some time ago. It turns out that Adafruit has a number of CircuitPython repos that are actually forks, which adabot has been missing due to the lack of searching for forks. This fixes that (but still only processes Adafruit repos).
- CoC Patch: After the "manual" update a couple days ago, there were some changes spotted. Luckily, now that they're all standard now (well, a few stragglers), we can git patch the changes.
Patch dry run:
```
$> python3 -m adabot.circuitpython_library_patches --local --dry-run 
-p 0001-update-code-of-conduct-discord-moderation-contact-sec.patch
.... Working directory: /home/sommersoft/Dev/adabot/adabot
.... Library directory: …
```
> Patch To Update Code of Conduct

- adabot/lib/circuitpython_library_validators.py
- requirements.txt
Remove use of eval.
Uses `packaging` library instead, to compare pylint versioning.
Addresses: https://github.com/adafruit/adabot/pull/149#pullrequestreview-373824327
> Update Pylint Validator

- adabot/update_cp_org_libraries.py
Needed a minor update so that the Pylint version validator will run for circuitpython.org/contributing.
> circuitpython.org: Implement Pylint Version Validator

- adabot/lib/circuitpython_library_validators.py
Fixes #146 
Originally I thought that they [re]moved the `permissions` field from the GitHub API response, but turns out that wasn't the issue. _My troubleshooting was with **un-authenticated** requests, which don't include the permissions field._
`validate_repo_state()` has been using the passed in `repo` variable which is generated via the Search API. It made its own call to the repos API, but none of the function used that response.
At some point though, the results passed in from the Search API (via `list_repos()`) started losing the `permissions` field. I'm not entirely sure if its a GitHub issue, or a `list_repos()` problem. But this works around it either way...
Result:
```
~/Dev/adabot/adabot:$> python3 -m adabot.circuitpython_libraries -v "validate_repo_state"
Running …
```
> Fix CircuitPythonLibrarians Permissions Validator

- patches/0001-build.yml-add-black-formatting-check.patch
Patching dry-run:
```
~/Dev/adabot/adabot:$> python3 -m adabot.circuitpython_library_patches --local --dry-run 
-p 0001-build.yml-add-black-formatting-check.patch
.... Working directory: /home/sommersoft/Dev/adabot/adabot
.... Library directory: /home/sommersoft/Dev/adabot/adabot/.libraries/
.... Patches directory: /home/sommersoft/Dev/adabot/adabot/patches/
.... Deleting any previously cloned libraries
.... Running Patch Checks On 239 Repos ....
. Skipping Adafruit_CircuitPython_BLE_BroadcastNet: patch does not apply
. Skipping Adafruit_CircuitPython_Bundle: patch does not apply
.... Patch Updates Completed ....
.... Patches Applied: 234
.... Patches Skipped: 2
.... Patches Failed: 3 
.... Patch Check Failure Report ....
>> Repo: …
```
> Patch: Add Patchfile To Add Black Code Style Check To build.yml

- adabot/lib/circuitpython_library_validators.py
Fixes #165
New short[er] list:
```
"repo_infrastructure_errors": {
"CircuitPython drivers page missing driver": [
"https://github.com/adafruit/Adafruit_CircuitPython_CPython",
"https://github.com/adafruit/Adafruit_CircuitPython_APDS9500",
"https://github.com/adafruit/Adafruit_CircuitPython_BLE_Adafruit",
"https://github.com/adafruit/Adafruit_CircuitPython_BLE_BerryMed_Pulse_Oximeter",
"https://github.com/adafruit/Adafruit_CircuitPython_BitbangIO"
],
"CircuitPythonLibrarians team missing or does not have write access": [
"https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel"
],
"Example file(s) missing sensor/library name": [
"https://github.com/adafruit/Adafruit_CircuitPython_BNO055",
"https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO"
],
"Failed to fetch latest release …
```
> Ignore Relevant Validators When 'setup.py.disabled' Exists

- adabot/lib/circuitpython_library_validators.py
This will allow underscores in example filenames, while not flagging them for not having the repo name in the example. There are two options included in this initial DRAFT PR.
**This draft will not work as submitted. Please let me know which of the following options is preferred.**
Strips underscores from repo name and example name, and makes comparison. This would allow example filenames to have both _additional_ and _missing_ underscores when compared to the repo name. Examples:
```
Checking featherwing against featherwing_tempmotion_simpletest.py
Repo name stripped of '_': featherwing
Rebuilt example name: featherwingtempmotion
Match: True
Checking display_shapes against display_shapes_simpletest.py
Repo name stripped of '_': displayshapes
Rebuilt example name: displayshapes
Match: …
```
> Allow Example Filename Underscore Variations Compared To Repo Name

- adabot/lib/circuitpython_library_validators.py
Weblate creates a single PR that can include contributions from multiple users.  The individual commits inside the PR have the actual contributor as the "author".  Ensure that these authors are credited individually.
Sometimes no "author" is listed; this appears to be because the gitcommit's author information does not match up to a github account. In one case, I see the author information is listed as "Anonymous <noreply@weblate.org>", which has no github user associated and ends up uncredited.
Testing performed: ran it locally and saw the translation author bergdahl credited.
```
Core
* 13 pull requests merged
* 9 authors - bergdahl, LearnWeaver, hierophect, xobs, maholli, WarriorOfWire, DavePutz, jepler, xiongyihui
* 4 reviewers - dhalbert, tannewt, jepler, hierophect
```
> gather_insights: if weblate created a PR, name all authors inside

- adabot/arduino_libraries.py
- adabot/lib/common_funcs.py
Fixes #169
- Use `github.get` vs direct `requests.get` on paginated results. Alleviates non-persistent authentication
- While looking into using a `requests.Session` to fix this, I came across requests' auto-parsing of `Link` headers and exposing them in the response object. I changed to using that to simplify navigating relational links.
> list_repos(): Persist GitHub Authentication & Simplify Relational Link Navigation

- adabot/circuitpython_libraries.py
- adabot/lib/circuitpython_library_validators.py
These descriptions improve social shares, and possibly search results.
Missing repository description - 60
* https://github.com/adafruit/Adafruit_CircuitPython_SK9822
* https://github.com/adafruit/Adafruit_CircuitPython_Debug_Bus_Device
* https://github.com/adafruit/Adafruit_CircuitPython_Debug_SPI
* https://github.com/adafruit/Adafruit_CircuitPython_74HC595
* https://github.com/adafruit/Adafruit_CircuitPython_ADXL34x
* https://github.com/adafruit/Adafruit_CircuitPython_APDS9500
* https://github.com/adafruit/Adafruit_CircuitPython_BD3491FS
* https://github.com/adafruit/Adafruit_CircuitPython_BH1750
* https://github.com/adafruit/Adafruit_CircuitPython_BluefruitConnect
* https://github.com/adafruit/Adafruit_CircuitPython_BMP3XX
* https://github.com/adafruit/Adafruit_CircuitPython_Debug_I2C …
> Print a warning for repos without descriptions

- patches/0003-actions-Remove-bad-whitespace-from-pylint-invocation.patch
.. this was removed in pylint 2.6.0 so there's no reason to silence it
> remove 'bad-whitespace' from pylint invocation

- adabot/lib/circuitpython_library_validators.py
- requirements.txt
Fixes #184
```
(.env) ~/Dev/adabot/adabot:$> python -m adabot.circuitpython_libraries -v "validate_passes_linting" -e 999
Running CircuitPython Library checks...
Report Date: 05 September 2020, 01:39PM
- Depth for listing libraries with errors: 999
- These validators will run: validate_passes_linting
Latest pylint is: 2.6.0
Found 260 repos to check.
Found 239 submodules in the bundle.
Failed PyLint checks - 48
* https://github.com/adafruit/Adafruit_CircuitPython_JTAG
* https://github.com/adafruit/Adafruit_CircuitPython_ATECC
* https://github.com/adafruit/Adafruit_CircuitPython_AWS_IOT
* https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT
* https://github.com/adafruit/Adafruit_CircuitPython_BLE_Eddystone
* https://github.com/adafruit/Adafruit_CircuitPython_BLE_Radio
* …
```
> Add Validator To Run Pylint On Libraries

- adabot/circuitpython_libraries.py
I think this may be what is needed to resolve #189. 
I tried testing it out locally by running `circuitpython_libraries.py` I found that I had to insert my github username somewhere to get it working. And once I did that it seemed to start running, but then reported hitting my github API rate limit and started sleeping for ~1hr before presumably continuing. 
I'm not certain what the rate limit is set to, nor how many calls this script is attempting to make, so I'm not sure if it's actually practical for me to be able to test it or not. 
Either way I am happy to add or change anything else that needs to get updated for this if someone can point me in the right direction.
> adding more blinka repos

- adabot/circuitpython_bundle.py
- adabot/lib/common_funcs.py
See issue for some history on this: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/issues/262 also this PR: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/pull/265
There was an attempt to add these docs link manually in the bundle repo. But it turned out that it needs to be done here in adabot.
This PR updates the script to include a docs link formatted the same as that original PR. I spot checked a few of the ones in the resulting md file and they were working correctly, but I did not do an exhaustive test of them.
Here is the md file that was generated when I tested this script locally:
[circuitpython_library_list.md.txt](https://github.com/adafruit/adabot/files/5503885/circuitpython_library_list.md.txt)
> Adding docs links to lib md

- adabot/circuitpython_bundle.py
- 4.x is deprecated, it probably should give 6.x as an example
- Explain why it's important to only selectively install libraries on non-Express boards
> Update release message

- adabot/lib/circuitpython_library_validators.py
This runs when update_cp_org_libraries.py is run and should work with circuitpython.org/contributing
> Added function to check that actions is passing

- adabot/lib/circuitpython_library_validators.py
- requirements.txt
Fixes #215
This grabs `.readthedocs.yml` content from `adafruit/cookiecutter-adafruit-circuitpython`, parses the YAML, and then compares each library's  parsed YAML to the cookicutter version.
Originally, I used some discovery via the GH API to get the cookiecutter version in an effort to avoid hardcoding the URL and being "futureproof". However, the code was cumbersome and essentially only used once per session. So...I hardcoded it. _Should_ be an easy update if the file/URL path ever changes.
An alternative, that doesn't involve additional dependencies, would be to just compare the raw text. Another benefit to raw text comparison is that it would also compare the license info.
There's no discernable increase in processing times, and there are no increases to GH API requests.
I would …
> Change Verification Method of .readthedocs.yml

- adabot/lib/circuitpython_library_validators.py
When retrieving the **merged** Pull Requests for weekly stats, only around 30 were retrieved on the core repository due to the default pagination of the results. But there is more than 100 issues and PRs updated every week these days, so a lot of them were missing.
The code to retrieve the **opened** pull requests already went through all the pages (using the 100 items per page max of the API), so I factored it out as a convenience function and used it in both places. Also the additional pages are now always retrieved with the `github_requests` module, avoiding a few hits to the unauthenticated rate limit (I think these were the last ones).
before (last weekly meeting notes)
> ### Overall
> * 40 pull requests merged
>   * 22 authors - jfurcean, hugodahl, dherrada, JPEWdev, tannewt, …
> Statistics: retrieve all merged commits and authors

- patches/0001-Moved-CI-to-Python-3.7.patch
We're doing this because a number of libraries are failing because they can't find libraries that are in Python 3.7 but not in 3.6
> Added python 3.7 CI patch

- patches/0001-Moved-CI-to-Python-3.7.patch
First one didn't work. I've tested this one locally with --dry-run and it does work and only fails on libraries that don't have a build.yml
> Added working python3.7 patch

- adabot/lib/circuitpython_library_validators.py
Tested by itself and with other adabot checks. It does print out like 250 libraries so I'm fine if we wait to merge until I'm further along with moving everything to main.
> Added check to ensure that all libraries use main as their default branch

- adabot/arduino_libraries.py
- adabot/circuitpython_libraries.py
- tests/integration/test_arduino_libraries.py
- tests/integration/test_circuitpython_libraries.py
@dherrada brought it to my attention that my last PR containing changes to allow/add tests, broke output file generation for reports.
The problem was the use of global scoped variables, that was broken by adding a `main` function.
This fix does what I should've done from the beginning, and utilizes `logging` to allow for multiple outputs.
Also added tests for output file generation.
> Fix Output File Generation For Reports

- adabot/lib/circuitpython_library_validators.py
Basically what was happening is that Adabot was searching for any PRs that had been updated in the last week, and not filtering out ones that were closed more than 7 days back.
Before: https://gist.github.com/dherrada/0721f6968d11178b6bd8a002ec6c42e4
Now: https://gist.github.com/dherrada/e7a68f86081657d536e1f741fa5bed8c
> Fixed merged pr check

- tests/integration/test_circuitpython_libraries.py
- tests/integration/test_update_cp_org_libraries.py
Fix typos, and follow up to https://github.com/adafruit/adabot/pull/237#issuecomment-915224439.
> Fix 'libraries' Typos

- adabot/circuitpython_libraries.py
- adabot/lib/circuitpython_library_validators.py
- adabot/update_cp_org_libraries.py
- tests/integration/test_update_cp_org_libraries.py
Fixes #238
Updates report to match desired result:
```
* 8 pull requests merged
* 6 authors - makermelissa, rdoursenaud, kattni, tannewt, Neradoc, lesamouraipourpre
* 8 reviewers - makermelissa, dhalbert, tannewt, antonio-openroad, TheKitty, FoamyGuy, ladyada, kattni
* Merged pull requests:
* https://github.com/adafruit/Adafruit_CircuitPython_MIDI/pull/41 (Days open: 36)
* https://github.com/adafruit/Adafruit_CircuitPython_BLE/pull/135 (Days open: 2)
* https://github.com/adafruit/Adafruit_CircuitPython_BLE_File_Transfer/pull/13 (Days open: 1)
* https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/pull/49 (Days open: 1)
* https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SH1107/pull/9 (Days open: 1)
* https://github.com/adafruit/Adafruit_CircuitPython_IS31FL3741/pull/2 …
```
> Update CircuitPython Report Order & Emergency Fix

- .github/workflows/learn_cron.yml
Typical workflow from within my fork (modified version so it would run in the fork):
https://github.com/jepler/adabot/runs/3883397046?check_suite_focus=true
Release created by it:
https://github.com/jepler/Adafruit_Learning_System_Guides/releases/tag/20211013
> Tag Learn nightly, so that new artifacts are released

- .github/workflows/learn_cron.yml
.. as well as release-on-push -- releasing learn on push to adabot doesn't make sense (but it was intended for my testing)
> restore usual fork protections

- patches/0001-Fixed-readthedocs-build.patch
Test PR:
https://github.com/adafruit/Adafruit_CircuitPython_BNO055/pull/93
Local test:
```
eherrada@eh:~/adafruit/temp/adabot$ python3 -m adabot.circuitpython_library_patches --dry-run -local -p 0001-Fixed-readthedocs-build.patch
.... Working directory: /home/eherrada/adafruit/temp/adabot
.... Library directory: /home/eherrada/adafruit/temp/adabot/.libraries/
.... Patches directory: /home/eherrada/adafruit/temp/adabot/patches/
.... Deleting any previously cloned libraries
.... Running Patch Checks On 305 Repos ....
. Skipping Adafruit_CircuitPython_BLE_File_Transfer: patch does not apply
. Skipping Adafruit_CircuitPython_GFX: patch does not apply
. Skipping Adafruit_CircuitPython_TestRepo: patch does not apply
. Skipping Adafruit_CircuitPython_VL53L1X: …
```
> Added patch for rtd building

- adabot/lib/circuitpython_library_validators.py
Pylint isn't being handled in build.yml anymore, so I made those checks relevant to .pre-commit-config.yaml and added a few more. I tested with testrepo and ran it locally. 
The pylint version in cookiecutter is different from the version in most repos so if merged this will say those libraries (almost all) have an incorrect pylint version.
> Added checks for pre-commit-config.yaml

- adabot/lib/circuitpython_library_validators.py
Previously, any file in examples/ needed to have the library name at the beginning. However, some libraries ([such as BNO055](https://github.com/adafruit/Adafruit_CircuitPython_BNO055/tree/main/examples)) have more complicated demos that need their own subdirectory and probably shouldn't all start with the repo name.
This change makes this ok as long as the subdirectory has the library name in it.
Before change (in examples/ dir):
```
├── bno055_i2c-gpio_simpletest.py
├── bno055_simpletest.py
└── bno055_webgl_demo
├── server.py
```
Not ok
```
├── bno055_i2c-gpio_simpletest.py
├── bno055_simpletest.py
└── bno055_webgl_demo
├── bno055_server.py
```
Ok (but not always possible)
```
├── bno055_i2c-gpio_simpletest.py
├── bno055_simpletest.py
└── webgl_demo
├── bno055_server.py
```
Ok
After …
> Changed examples dir check to be satisfied if repo name is at beginning of file or subdir containing file

- patches/05302022_set_doc_language.patch
Fixes issue with Sphinx 5.0.0 where `language` cannot be explicitly set to `None`.  Now, the language is set to English (`"en"`).
Associated draft PR: https://github.com/adafruit/Adafruit_CircuitPython_BNO055/pull/105
Works on all but 6 libraries, so easy to manually patch up afterwards!
> Add patch for fixing language setting in docs/conf.py

- patches/0001-Removed-duplicate-code-from-library-pylint-disable.patch
44 libraries have duplicate-code disabled for the pylint check on the libraries. This patch will remove that for those libraries.
> Added patch to remove duplicate code from libs that have it

- tools/ci_status.py
- tools/docs_status.py
- tools/git_functionality.py
- tools/iterate_libraries.py
Updates the tools for checking CI Actions and RTD docs build status into CLI tools.  This means they can be added to a CI workflow for building the bundle, or even just in their own regularly scheduled CI to check these things.  They would work like `pre-commit` hooks, in this way.
> Turn some tools into CLI tools

- .github/workflows/reports_cron.yml
- adabot/arduino_libraries.py
- adabot/circuitpython_bundle.py
- adabot/circuitpython_libraries.py
- adabot/circuitpython_library_download_stats.py
- adabot/lib/assign_hacktober_label.py
- adabot/lib/blinka_funcs.py
- adabot/lib/circuitpython_library_validators.py
- adabot/lib/common_funcs.py
- adabot/update_cp_org_libraries.py
- requirements.txt
- tools/README.md
Uses a version of the code I made for `tools/` to better check the RTD docs build status and GitHub Actions CI status.  Hooks into adabot the same way as all the other checks so circuitpython.org gets the issues populated.
Also fixes the companion CLI tools that do the same.
> Update docs and CI checks

- requirements.txt
Based on what I'm seeing here, I think a mismatch between the version of `pylint` being used within adabout on the libraries, and what the version the `pre-commit` hooks are running is likely causing some false failures to show up on circuitpython.org.  This changes pins the dependency to the same version that the hooks use, which means they should align more closely (hopefully 1:1!)
> Pin the pylint version to what the libraries are using

- patches/09AUG2022-setuptools-scm.patch
Patch for adding `setuptools-scm` as build system requirement in `pyproject.toml`.
Draft PR (sorry it isn't the BME library, I was using one of the libraries I noticed the problem on and could test):
https://github.com/adafruit/Adafruit_CircuitPython_NeoTrellis/pull/21
> Add patch for adding setuptools-scm to pyproject.toml

- adabot/lib/circuitpython_library_validators.py
This should be approved before the switchover to `pyproject.toml` files, and merged only just before the switch happens (within the same day).
> Swtich adabot over to working with pyproject.toml files

- adabot/lib/circuitpython_library_validators.py
- tests/conftest.py
- tests/integration/test_circuitpython_libraries.py
Fixes the issue where the CI can't test certain validators in pull requests because secrets cannot be passed to them.  Instead, this will have to be done locally, which should be a decent workaround if they ever need to be tested during development.
> Allow for using pytest with/without tokens

- adabot/lib/circuitpython_library_validators.py
The valdiators for checking the RTD build status weren't resilient to API rate limiting, so this adds that flexibility in, rather than have it think it's failed to load the RTD build status.
> Improve throttling flexibility

- adabot/lib/circuitpython_library_validators.py
- Now raises error if `setup.py` is found in the repo (should be using `pyproject.toml`)
- Now raises error if `pyproject.toml` is not present (regardless of presence of `pyproject.toml.disabled`
> PyPI infrastructure checks

- adabot/circuitpython_libraries.py
Fixes the issue where the reports say there are -2 issues unassigned to milestone.  This changes the math that was happening to a simple API call to the core repository.
> Use API call to find unassigned issues in core

- adabot/lib/circuitpython_library_validators.py
For the life of me, I cannot figure out why adabot is struggling with the RTD validation.  This PR breaks out the potential errors for better diagnosing since doing it locally doesn't seem to be helping.  No behavior is changed, just the resulting errors attributed to the failures.
> Specify errors for docs validation

- adabot/circuitpython_libraries.py
Fixes formatting for the new/updated libraries section of the weekly meeting text.  I attached a file showing what it should be after this change.
[circuitpython_library_report_20220907.md](https://github.com/adafruit/adabot/files/9523042/circuitpython_library_report_20220907.md)
> Fix new/updated libraries formatting

- adabot/lib/circuitpython_library_validators.py
This should be the cause of the current failure in the Library Infrastructure Issues page on circuitpython.org
After merging, circuitpython-org will need to be updated to include this change.
> Fix getting repo using PyGithub

- adabot/circuitpython_libraries.py
Fixes the issue introduced in #297 which accidentally removed the code that printed the active milestones for the core and their issues counts.  Whoever wrote that PR should have realized that 😆
> Readd printing active milestones and their issue counts

- adabot/circuitpython_libraries.py
- adabot/circuitpython_library_download_stats.py
- requirements.txt
Adds the PyPI stats to the daily report, which it pulls from Google's BigQuery.  Passed the `pytest` cases locally.
I'll work on have this auto-push commits to the bundle next.
> Add weekly PyPI stats to daily report

- adabot/lib/circuitpython_library_validators.py
Fixed a bug in adabot for checking the latest CI run result.  It does not return a boolean, but rather a string, so it needs to check the value and not just the truthiness.
> Fix actions success check

- adabot/lib/circuitpython_library_validators.py
New pylint, new update to adabot!
Fixes the check adabot does to compare to the newly updated version.
> Update pylint version check reference

- adabot/lib/circuitpython_library_validators.py
Fix to adabot for https://github.com/adafruit/circuitpython-org/issues/1102
> Fix validator if no CI runs

- .github/workflows/bundle_cron.yml
Noticed the daily report consisted of the same downloads as the previous 7 day window - turns out the file wasn't being updated due to the workflow failing.
> Pass through secrets to environment for workflow

- adabot/lib/circuitpython_library_validators.py
Resolves #316 by adding `(draft)` at the end of draft PRs listed.
> Add draft status to PR lists

- adabot/circuitpython_bundle.py
Since bundles do seem to be updating, I think the now failing CI for updating bundles was actually failing when it was looking at the Community bundle, which didn't update anything but marked it as such. This should resolve that issue. I don't think there was any impact to either bundle, which is good.
> Only mark updates if they are made

- adabot/circuitpython_libraries.py
- adabot/lib/community_bundle_announcer.py
More love for the community bundle!  This resolves #201 by adding an announcement in the "Libraries" section if any of the community bundle libraries are new or updated within the last seven days.
I implemented it in a different way than it checks the Adafruit Bundle because that way uses a couple calls for each library, whereas this this only makes a couple requests to GitHub (600 vs 2).  Might be worth switch to using this method for the others as well.
> Announce community bundle updates

- adabot/circuitpython_libraries.py
- adabot/lib/bundle_announcer.py
Resolves #330
Uses less GitHub API calls by checking the latest release in the Bundle for information on new and updated libraries.
> Improve library update check for Adafruit Bundle libraries

- patches/01192023_release_patch.patch
Fixes the patch file for #332 retroactively, as I was able to use it and have already started the patch.
> Fix patch file

- .github/workflows/bundle_cron.yml
- .github/workflows/learn_cron.yml
- .github/workflows/pre-commit.yml
- .github/workflows/reports_cron.yml
- .github/workflows/test.yml
- Updates `actions/setup-python` and `actions/checkout` to the current versions to avoid deprecation warnings.
- Removes the steps where the GitHub context is dumped, which GitHub does not recommend doing.
> Update CI files

- .github/workflows/reports_cron.yml
This allows the report CI to be run on demand.  Doesn't upload reports to AWS S3 in that case.
> Allow running reports CI on demand

- adabot/circuitpython_libraries.py
Preliminary step to fixing https://github.com/adafruit/circuitpython-org/issues/1136, which will delete this page.
> Remove link to core download stats page

- .gitignore
- tools/ci_status.py
- tools/iterate_libraries.py
- tools/run_black.sh
Adds new tooling I've created and used for forcing CI reruns
> Tooling update

- patches/14MAY2023_pylintrc_jquery.patch
- Updates `.pylintrc` to fix `pylint` warning for specifying exceptions in `overgeneral-exceptions`
- Fixes jQuery for Sphinx
Paired with https://github.com/adafruit/cookiecutter-adafruit-circuitpython/pull/228
> Add patch for pylint, jQuery

- adabot/arduino_libraries.py
This removes the hardcoded branch name of master from the arduino library checking file. 
Also minor change to reuse processed JSON variable.
> Fix: master branch to repo["default_branch"]

- adabot/github_requests.py
- adabot/update_cp_org_libraries.py
We still don't know what exactly is causing #263 -- a recent log showed some odd attempt to sleep to avoid a rate limit, but then no further activity was shown for several hours until the job was terminated, much longer than the expected sleep:
```
Fri, 24 Nov 2023 09:20:27 GMT  - Report output will be saved to: /home/runner/work/circuitpython-org/circuitpython-org/bin/adabot/libraries.v2.json
Fri, 24 Nov 2023 10:06:30 GMT GitHub API Rate Limit reached. Pausing until Rate Limit reset.
Fri, 24 Nov 2023 10:20:39 GMT Rate Limit will reset at: 2023-11-24 10:20:39
Fri, 24 Nov 2023 10:20:39 GMT GitHub API Rate Limit reached. Pausing until Rate Limit reset.
Fri, 24 Nov 2023 10:20:39 GMT Rate Limit will reset at: 2023-11-24 10:20:39
Fri, 24 Nov 2023 15:20:09 GMT Error: The operation was canceled. …
```
> turn up the debug level

- patches/11OCT2023-add-sphinx-rtd-theme-to-docs-reqs.patch
patch that adds `sphinx-rtd-theme` into `docs/requirements.txt` which is needed since a change in RTD behavior starting 10/3 outlined in this post: https://blog.readthedocs.com/defaulting-latest-build-tools/ 
For our usage the crux is that `sphinx-rtd-theme` used to be installed automatically, but no longer is so we need to specify it in a requirements file in order for it to be installed moving forward.
> adding patch for sphinx-rtd-theme in docs/reqs

- adabot/circuitpython_bundle.py
* Suggest use of circup
* Mention to use bundle-py not 'source code'
Closes: adafruit/Adafruit_CircuitPython_Bundle#450
> Improve bundle release notes

- .pre-commit-config.yaml
- adabot/lib/circuitpython_library_validators.py
- requirements.txt
- tools/library_functions.py
#370 failed because of a version conflict...
> bump black, packaging versions

- .pre-commit-config.yaml
- adabot/lib/circuitpython_library_validators.py
- requirements.txt
- tools/ci_status.py
While looking into an issue with a generated report I had trouble getting adabots requirements installed locally in python 3.12. Updating the version of pylint to a newer one allows it to work under py3.12.  The version of pylint that pre-commit uses is specified separately and also has been updated. 
The other changes are to resolve the 2 pylint issues that get flagged by the newer version.
> Use newer pylint

- adabot/lib/bundle_announcer.py
For some reason some of the lib strings have a `\r` at the end of them i.e. 
```
"[ticks](https://github.com/adafruit/Adafruit_CircuitPython_Ticks/releases/1.1.0)\r"
```
That causes `parse.parse()` to return `None` instead of the matched variables. Which then raises an exception 2 lines later when an attempt to access `comps["link_comp"]`.
This resolves it by calling `.strip()` prior to `parse()` so that the string value will match the pattern that parse is expecting.
I tested it successfully by running `python3 -m adabot.circuitpython_libraries` with the appropriate env variables set up.
> strip lib string before parse

- .github/workflows/bundle_cron.yml
- .github/workflows/pre-commit.yml
- .github/workflows/test.yml
- adabot/arduino_libraries.py
- adabot/circuitpython_bundle.py
- adabot/github_requests.py
When the remaining rate limit is missing, we assumed we were out (`0`). This broke later when we tried to wait until we had more requests. Now we'll assume we have remaining requests instead.
Also, update to latest Python and remove more Redis leftovers.
> Fix update bundles

- patches/0001-remove-deprecated-get_html_theme_path-call.patch
The newest version of sphinx-rtd-themes has deprecated a function call that was made in our docs/conf.py files which causes the docs build to fail.  Stacktrace can be seen here: https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/actions/runs/11217110767/job/31177912073#step:2:1002
This removes the deprecated function call. The error message indicates that it is safe to remove it if it's being used to set this variable. 
A local docs build inside of Display_Text library was able to build successfully with this change.
> added patch to remove deprecated sphinx function call.

- patches/0001-remove-deprecated-get_html_theme_path-call-alt-config.patch
There were 9 repos that have a different variation of the theme configuration in their docs/conf.py file. Here is an example of one of them: https://github.com/adafruit/Adafruit_CircuitPython_AMG88xx/blob/main/docs/conf.py#L152-L162
This patch file should update those 9 with the same fix for sphinx theme deprecation.
> patch to remove sphinx function call alternative config file

- .github/workflows/bundle_cron.yml
- adabot/circuitpython_bundle.py
- requirements.txt
Resolves: #377
This adds a new job to the bundle cron action which builds both the community and adafruit bundles. 
The `update-bundles` job has had `needs: test-bundle-builds` added to it so that it depends upon the prior test builds job. If that test build fails then update-bundles will be skipped. 
I tested this to the best of my abilities in a test repo. There are a few failed runs visible here: https://github.com/FoamyGuy/adabot_actions_tests/actions which validated the way that `needs` will skip the job if it's dependency failed. For testing I modified the task to add an erroneous extra file into one of the libraries similarly to what caused the recent build failures.
That being said, I'm not sure if there is a great way to test it within the cron task context without just merging …
> Test bundle builds job before push

- adabot/circuitpython_bundle.py
Recently, we changed adabot to experimentally build the bundle before pushing it.
This is great, as it will hopefully avoid pushing broken bundles, which cause more problems down the line compared to just not having an updated bundle.
However, this change caused circuitpython-build-tools to create a path "build_deps" with some files inside it, and adabot *added* those files. (https://github.com/adafruit/Adafruit_CircuitPython_Bundle/commit/91e3ce1477f90e702639f188e2f839e3b2e28953)
Since an adabot bundle update should only ever change tracked files, change how git is invoked so that it does not add untracked files.
> Don't add untracked files in an adabot bundle update

- adabot/circuitpython_library_release.py
- requirements.txt
This removes the "manual" generation of release notes template file in favor of using the auto generated release notes that Github provides which will automatically include information about any PRs that have been merged for that release as well as a difference link. 
It also adds `--title` argument to the CLI which can be used in order to set the title from the command line rather than having to dive into the code file and edit a hardcoded value.
> Generated release notes & --title argument

- adabot/circuitpython_libraries.py
- adabot/lib/common_funcs.py
@ladyada 
resolves: #380 and #387
Removed the hacktoberfest per issue stats because we apply it at the repo level now. 
Changed the docs link to also check for the newer style docs.circuitpython.org URL.
> Remove hacktober issues & fix docs link in list

- adabot/__init__.py
- adabot/arduino_libraries.py
- adabot/circuitpython_libraries.py
- adabot/circuitpython_library_download_stats.py
- adabot/circuitpython_library_patches.py
- adabot/circuitpython_library_release.py
- adabot/lib/assign_hacktober_label.py
- adabot/lib/circuitpython_library_validators.py
- adabot/lib/common_funcs.py
- adabot/pypi_requests.py
- tools/docs_status.py
- tools/file_compare.py
- tools/find_text.py
@ladyada 
Supersedes #366.
Looking back through comments and PRs related to the very long-lasting and sometimes failing actions tasks I realized that #366 was never merged. 
The default behavior for requests does not use a connect or read timeout and can hang forever if a requests fails in certain ways. 
Trying to recall my mindset from the time #366 was submitted I think my theory was that when we see the task run for the very long period and still not succeed that it may have been getting stuck in one of these hang forever due to failed request cases. Explicitly setting timeout values for all requests calls should prevent that if it is indeed what is happening. 
The other stuff from 366 is no longer relevant and was causing merge conflicts with the new way that release notes get …
> Requests timeout

- adabot/circuitpython_bundle.py
- adabot/lib/common_funcs.py
@ladyada 
Resolves: https://github.com/adafruit/CircuitPython_Community_Bundle/issues/118
I tried to test this as best as possible, however all of it is kicked off by a higher level auto cron task that includes the releasing so I can only validate the smaller components easily. 
I tested the updated list md generating code locally for both community bundle and adafruit bundle and the files seem good to me. 
My understanding of the way the cron task works is the next run after this is merged will create and push `circuitpython_community_auto_library_list.md` into the Community bundle repo.  That file will get updated each time the task runs with any changes to the bundle. 
I made it a separate file with "auto" in the name because it compares to the existing content of the file and the …
> Automate community bundle list

- adabot/lib/circuitpython_library_validators.py
In trying to understand the example naming rules based on the https://circuitpython.org/contributing/library-infrastructure-issues page and the Good First Issue to begin contributing.  I ran across these repos in the list of _missing sensor/library name:_. These look to be false positives since the names in the examples directories match the naming description on the https://circuitpython.org/contributing/library-infrastructure-issues page 
https://github.com/adafruit/Adafruit_CircuitPython_Requests 
the examples directory consists of more directories, however each directory contains correctly named files, i.e. requests_xxx.py
https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI
here there is a mix of directories and files, although again all the example .py files are correctly …
> Example naming

- patches/0001-add-sphinx-configuration-to-rtd.yaml.patch
this addresses the fact that rtd.yaml files lacking sphinx configuration are being deprecated: https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
The same change in cookiecutter is PR'd here: https://github.com/adafruit/cookiecutter-adafruit-circuitpython/pull/246
https://github.com/adafruit/Adafruit_CircuitPython_MPU6050/pull/40 draft is opened to confirm that actions are all good. This was the library / branch that the patch file was created from.
> adding patch for sphinx configuration in rtd.yaml

- adabot/lib/circuitpython_library_validators.py
The Read the docs get builds API can return an empty results set. 
`{
"count": 0,
"next": null,
"previous": null,
"results": []
}`
This causes an exception in the validator due to no check for empty set.
This simple change checks and handles that empty set
This was the cause of the bulk of the _A programmatic error occurred_ in the Library Infrastructure report
> RTD results can cause exception

- adabot/github_requests.py
- adabot/lib/bundle_announcer.py
- adabot/lib/circuitpython_library_validators.py
- adabot/lib/common_funcs.py
This is an attempt to fix the issue causing the actions to hang sometimes such as: https://github.com/adafruit/circuitpython-org/actions/runs/14512434132
My hypothesis is that this issue is caused by different parts of the code handling of waiting for the rate limit reset time. I think there is a situation where some parts of the code end up sleeping for a very long time due to a "negative overflow" from subtracting dates. 
I found this section of the log at the end of the failed / stalled actions run:
```
2025-04-17T09:57:55.2025426Z GitHub API Rate Limit reached. Pausing until Rate Limit reset.
2025-04-17T09:57:55.2025809Z Rate Limit will reset at: 2025-04-17 10:23:13
2025-04-17T09:57:55.2026084Z Sleeping 1517 seconds
2025-04-17T10:23:13.3062291Z Resetting dropped connection: …
```
> Attempt to fix actions hang

- .github/workflows/bundle_cron.yml
- .github/workflows/learn_cron.yml
- .github/workflows/reports_cron.yml
- .github/workflows/test.yml
- adabot/github_requests.py
Override `response.json()` with a version that catches JSON decode errors, logs them, and attempts to continue on. 
Depending on which part of the code called `json()` this could still halt the action, but it seems many places check `if "key" in response_data` and should be able to continue running in the event of a decode error on a single request in the middle of compiling a report. 
Also updated versions of: 
- python in the reports container
- actions checkout and setup-python
> JSON response exception handling & update actions versions

- adabot/lib/circuitpython_library_validators.py
changing the check for `.pylintrc` to `ruff.toml` instead.
> update lint config check for ruff

- patches/0001-update-rtd.yml-file.patch
patch from the change that was made in a single library here: https://github.com/adafruit/Adafruit_CircuitPython_FT5336/pull/9
> patch to update rtd.yml os version to ubuntu-lts-latest
